version: "3"
services:
    db:
      image: postgres
      volumes:
        - ./data/db:/var/lib/postgresql/data
      env_file:
        - .env
    web:
        build:
            context: .
        ports:
            - "8000:8000"
        command: >
            sh -c "python manage.py wait_for_db && python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
        volumes:
          - ./:/code
        env_file:
            - .env
    redis:
      image: redis
      container_name: redis
      ports:
        - "6379:6379"
      volumes:
        - ./co_redis/data:/data


    celery:
      build:
        context: .
        dockerfile: Dockerfile
      command: "celery -A app worker -l info"
      depends_on:
        - web
        - redis
        - db
      restart: on-failure
      env_file:
        - .env

    celery-beat:
      build:
        context: .
        dockerfile: Dockerfile
      command: "celery -A app beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
      depends_on:
        - web
        - redis
        - db
      restart: on-failure
      env_file:
        - .env
