# Generated by Django 5.0.2 on 2024-02-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scraper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("odometer", models.IntegerField()),
                ("username", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15)),
                ("image_url", models.URLField(max_length=255, unique=True)),
                ("images_count", models.IntegerField()),
                ("car_number", models.CharField(max_length=20)),
                ("car_vin", models.CharField(max_length=20)),
                ("datetime_found", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
